# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iss.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 458)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.astrounaunts = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.astrounaunts.setFont(font)
        self.astrounaunts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.astrounaunts.setText("")
        self.astrounaunts.setObjectName("astrounaunts")
        self.gridLayout.addWidget(self.astrounaunts, 1, 0, 1, 1)
        self.iss_position = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.iss_position.setFont(font)
        self.iss_position.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.iss_position.setText("")
        self.iss_position.setAlignment(QtCore.Qt.AlignCenter)
        self.iss_position.setObjectName("iss_position")
        self.gridLayout.addWidget(self.iss_position, 1, 1, 1, 1)
        self.get_location = QtWidgets.QPushButton(self.centralwidget)
        self.get_location.setObjectName("get_location")
        self.gridLayout.addWidget(self.get_location, 3, 1, 1, 1)
        self.get_astrounaunts = QtWidgets.QPushButton(self.centralwidget)
        self.get_astrounaunts.setObjectName("get_astrounaunts")
        self.gridLayout.addWidget(self.get_astrounaunts, 3, 0, 1, 1)
        self.iss = QtWidgets.QLabel(self.centralwidget)
        self.iss.setText("")
        self.iss.setAlignment(QtCore.Qt.AlignCenter)
        self.iss.setObjectName("iss")
        self.gridLayout.addWidget(self.iss, 0, 0, 1, 1)
        self.location_map = QtWidgets.QLabel(self.centralwidget)
        self.location_map.setText("")
        self.location_map.setAlignment(QtCore.Qt.AlignCenter)
        self.location_map.setObjectName("location_map")
        self.gridLayout.addWidget(self.location_map, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 22))
        self.menubar.setObjectName("menubar")
        self.menuDownload_Information = QtWidgets.QMenu(self.menubar)
        self.menuDownload_Information.setObjectName("menuDownload_Information")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGet_Astronaunts = QtWidgets.QAction(MainWindow)
        self.actionGet_Astronaunts.setObjectName("actionGet_Astronaunts")
        self.actionGet_Location = QtWidgets.QAction(MainWindow)
        self.actionGet_Location.setObjectName("actionGet_Location")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuDownload_Information.addAction(self.actionGet_Astronaunts)
        self.menuDownload_Information.addAction(self.actionGet_Location)
        self.menubar.addAction(self.menuDownload_Information.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Who\'s in Space and Where is the ISS"))
        self.get_location.setText(_translate("MainWindow", "Get Location"))
        self.get_astrounaunts.setText(_translate("MainWindow", "Get Astronaunts"))
        self.menuDownload_Information.setTitle(_translate("MainWindow", "Download Information"))
        self.actionGet_Astronaunts.setText(_translate("MainWindow", "Get Astronaunts"))
        self.actionGet_Location.setText(_translate("MainWindow", "Get Location"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
